### ISSUE TITLE
[FEAT] Java 21

### ISSUE THREAD

**Issue by fkjaekel** [arolfes/ansible-role-graalvm#41]
please add support to java 21

thanks

**Comment by arolfes** [comment]
Hey @fkjaekel ,
at least someone uses this ansible role. That's makes me happy. 


Unfortunately some major things changed in the download url and I have to adopt it.

so what will happen when I'm done:

support only for graalvm-community-jdk-editions

to demonstrate this "big" change for my little ansible role I will create a new release tag 2.0.0

But I think I can't do this all today.
It will take at least tomorrow as well

**Comment by arolfes** [comment]
Hi @fkjaekel, I made some progress
https://github.com/arolfes/ansible-role-graalvm/actions/runs/6297560008
a new release will come today

**Comment by arolfes** [comment]
Hello @fkjaekel,
the release is there. 
be aware there was a bigger change to support graal jdk 21.0.0

**the important things are:**
* the variable `graalvm_version` does no longer exists
* the variable `graalvm_java_version` must contain the full jdk version
   * example: 17.0.7, 17.0.8, 20.0.1, 20.0.2 or 21.0.0
   * previously it was only 17 or 11
* the variable `graalvm_architecture` is new
   * default value: `x64` which stands for `amd64` 
   * other possible value `aarch64`

The default version is `21.0.0`
the default install dir is `/opt/graalvm/jdk-21.0.0/`

If you face any issues, please let me know
